image: Visual Studio 2019
before_build:
  - nuget restore
build_script:
 - choco install "sonarscanner-msbuild-net46" -y
 - SonarScanner.MSBuild.exe begin /k:"FeedbackMessages" /d:sonar.cs.opencover.reportsPaths="Tests/coverage.xml" /d:"sonar.host.url=https://sonarcloud.io" /o:%SONAR_ORG_KEY% /d:sonar.login=%SONAR_TOKEN%
 - msbuild /verbosity:quiet "FeedbackMessages.sln"
test_script:
 - .\packages\OpenCover.4.7.922\tools\OpenCover.Console.exe -register:administrator -target:"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" -targetargs:"Tests\FeedbackMessages.Test\bin\Debug\FeedbackMessages.Test.dll" -excludedirs:"Examples" -output:"Tests\coverage.xml"
 - .\packages\OpenCover.4.7.922\tools\OpenCover.Console.exe -register:administrator -target:"C:\Program Files\dotnet\dotnet.exe" -targetargs:"test C:\projects\feedbackmessages\Tests\FeedbackMessages.AspNetCore.Test\FeedbackMessages.AspNetCore.Test.csproj" -mergeoutput -output:"Tests\coverage.xml" -excludedirs:"Examples" -oldstyle
 - .\packages\OpenCover.4.7.922\tools\OpenCover.Console.exe -register:administrator -target:"C:\Program Files\dotnet\dotnet.exe" -targetargs:"test C:\projects\feedbackmessages\Tests\FeedbackMessages.AspNetCore3.Test\FeedbackMessages.AspNetCore3.Test.csproj" -mergeoutput -output:"Tests\coverage.xml" -excludedirs:"Examples" -oldstyle
 - .\packages\OpenCover.4.7.922\tools\OpenCover.Console.exe -register:administrator -target:"C:\Program Files\dotnet\dotnet.exe" -targetargs:"test C:\projects\feedbackmessages\Tests\FeedbackMessages.AspNetCore.Blazor.Test\FeedbackMessages.AspNetCore.Blazor.Test.csproj" -mergeoutput -output:"Tests\coverage.xml" -excludedirs:"Examples" -oldstyle
after_test:
 - set JAVA_HOME=C:\Program Files\Java\jdk11
 - SonarScanner.MSBuild.exe end /d:sonar.login=%SONAR_TOKEN%
 
